-- ============================================================
-- Migration 015: Community, Parking, ESG & Phase 3/4 Tables
-- ============================================================
-- Covers Phase 3 (Scale) and Phase 4 (Platform) schema:
--   Module P  — Community Hub (posts, replies, moderation, votes)
--   Module N  — Parking / Non-charging P2P listings
--   Module O  — ESG / Carbon data products
--   Module Q  — White-label & partner API tenants
--   Module S  — V2G / Grid services (scheduling hooks)
--   Driver Plus subscription tracking
--   OCPI interoperability roaming sessions
--
-- All monetary values in pence (INT). No floats.
-- Depends on: migrations 001–014.
-- ============================================================


-- ============================================================
-- MODULE P — COMMUNITY HUB
-- AI-first EV community. Every post answered in < 3 seconds.
-- ============================================================

CREATE TYPE community_post_type AS ENUM (
    'question',        -- Ask & Answer Hub
    'tip',             -- tip / how-to
    'report',          -- fault / issue report (links to listing or area)
    'discussion',      -- open discussion
    'emergency_help',  -- SOS channel post
    'expert_insight'   -- installer / tariff expert contribution
);

CREATE TYPE community_post_status AS ENUM (
    'pending_moderation',  -- awaiting AI/human review
    'published',           -- live and visible
    'removed',             -- removed by moderation
    'locked'               -- no further replies allowed
);

CREATE TYPE community_reply_type AS ENUM (
    'ai_instant',          -- auto-generated by AI community agent
    'human',               -- written by platform user
    'expert'               -- from a verified expert (installer, advisor)
);

CREATE TYPE community_report_reason AS ENUM (
    'spam',
    'offensive',
    'misinformation',
    'off_topic',
    'other'
);


-- Community posts
CREATE TABLE community_posts (
    id              UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
    author_user_id  UUID                    NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    type            community_post_type     NOT NULL DEFAULT 'question',
    status          community_post_status   NOT NULL DEFAULT 'pending_moderation',

    title           VARCHAR(200)            NOT NULL,
    body            TEXT                    NOT NULL,

    -- Voice post: stores the original transcription
    is_voice_post   BOOLEAN                 NOT NULL DEFAULT FALSE,
    voice_audio_url TEXT,                    -- optional: store Whisper transcription source

    -- Tags / classification (added by AI at post time)
    tags            TEXT[]                  NOT NULL DEFAULT '{}',
    -- e.g. ['octopus_agile', 'zappi', 'london', 'billing']

    -- Listing/region association
    listing_id      UUID                    REFERENCES charger_listings(id) ON DELETE SET NULL,
    region_code     VARCHAR(10),            -- e.g. 'GB-LND', 'GB-MCR'

    -- Engagement
    view_count      INT                     NOT NULL DEFAULT 0,
    reply_count     INT                     NOT NULL DEFAULT 0,
    upvote_count    INT                     NOT NULL DEFAULT 0,
    is_answered     BOOLEAN                 NOT NULL DEFAULT FALSE, -- has an accepted/verified reply

    -- AI moderation verdict
    ai_moderation_score     NUMERIC(4,3),   -- 0.000–1.000 safety score
    ai_moderation_reason    TEXT,           -- why it was flagged or passed

    -- Pinning / featured
    is_pinned       BOOLEAN                 NOT NULL DEFAULT FALSE,
    pinned_by_user_id UUID                  REFERENCES users(id),

    created_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_community_posts_author     ON community_posts (author_user_id, created_at DESC);
CREATE INDEX idx_community_posts_status     ON community_posts (status) WHERE status = 'published';
CREATE INDEX idx_community_posts_type       ON community_posts (type, created_at DESC);
CREATE INDEX idx_community_posts_tags       ON community_posts USING GIN (tags);
CREATE INDEX idx_community_posts_listing    ON community_posts (listing_id) WHERE listing_id IS NOT NULL;
CREATE INDEX idx_community_posts_region     ON community_posts (region_code) WHERE region_code IS NOT NULL;
CREATE INDEX idx_community_posts_unanswered ON community_posts (created_at DESC) WHERE is_answered = FALSE AND status = 'published';

CREATE TRIGGER trg_community_posts_updated_at
    BEFORE UPDATE ON community_posts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- Community replies
CREATE TABLE community_replies (
    id              UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id         UUID                    NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
    author_user_id  UUID                    REFERENCES users(id) ON DELETE SET NULL,   -- NULL for AI replies
    parent_reply_id UUID                    REFERENCES community_replies(id) ON DELETE CASCADE, -- nested replies

    type            community_reply_type    NOT NULL DEFAULT 'human',
    body            TEXT                    NOT NULL,

    -- For AI replies
    ai_model_used   VARCHAR(50),            -- e.g. 'gpt-4o'
    ai_confidence   NUMERIC(4,3),           -- 0.000–1.000

    -- For expert replies
    expert_credential VARCHAR(100),         -- e.g. 'OZEV Certified Installer', 'Tariff Adviser'

    -- Engagement
    upvote_count    INT                     NOT NULL DEFAULT 0,
    is_accepted     BOOLEAN                 NOT NULL DEFAULT FALSE,    -- marked by post author
    is_verified     BOOLEAN                 NOT NULL DEFAULT FALSE,    -- 3+ upvotes = community-verified

    is_removed      BOOLEAN                 NOT NULL DEFAULT FALSE,
    removal_reason  TEXT,

    created_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_community_replies_post     ON community_replies (post_id, created_at ASC);
CREATE INDEX idx_community_replies_author   ON community_replies (author_user_id) WHERE author_user_id IS NOT NULL;
CREATE INDEX idx_community_replies_accepted ON community_replies (post_id) WHERE is_accepted = TRUE;

CREATE TRIGGER trg_community_replies_updated_at
    BEFORE UPDATE ON community_replies
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- Community votes (upvotes on posts and replies, one per user per item)
CREATE TABLE community_votes (
    id              BIGSERIAL   PRIMARY KEY,
    user_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_id         UUID        REFERENCES community_posts(id) ON DELETE CASCADE,
    reply_id        UUID        REFERENCES community_replies(id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_vote_post  UNIQUE (user_id, post_id),
    CONSTRAINT uq_vote_reply UNIQUE (user_id, reply_id),
    CONSTRAINT chk_vote_target CHECK (
        (post_id IS NOT NULL AND reply_id IS NULL) OR
        (post_id IS NULL AND reply_id IS NOT NULL)
    )
);

CREATE INDEX idx_community_votes_post  ON community_votes (post_id)  WHERE post_id IS NOT NULL;
CREATE INDEX idx_community_votes_reply ON community_votes (reply_id) WHERE reply_id IS NOT NULL;


-- Community reports (abuse / misinformation flags)
CREATE TABLE community_reports (
    id              BIGSERIAL               PRIMARY KEY,
    reporter_user_id UUID                   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_id         UUID                    REFERENCES community_posts(id) ON DELETE CASCADE,
    reply_id        UUID                    REFERENCES community_replies(id) ON DELETE CASCADE,
    reason          community_report_reason NOT NULL,
    detail          TEXT,
    resolved        BOOLEAN                 NOT NULL DEFAULT FALSE,
    resolved_by     UUID                    REFERENCES users(id),
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_report_target CHECK (
        (post_id IS NOT NULL AND reply_id IS NULL) OR
        (post_id IS NULL AND reply_id IS NOT NULL)
    )
);

CREATE INDEX idx_community_reports_unresolved ON community_reports (created_at DESC) WHERE resolved = FALSE;


-- ============================================================
-- MODULE N — PARKING / NON-CHARGING P2P LISTINGS
-- Hosts can list parking bays without a charger.
-- Charges by the hour/day. Future: EV-priority parking.
-- ============================================================

CREATE TYPE parking_listing_status AS ENUM (
    'draft',
    'published',
    'paused',
    'archived'
);

CREATE TYPE parking_price_unit AS ENUM (
    'per_hour',
    'per_day',
    'per_session'     -- fixed price regardless of duration
);

CREATE TABLE parking_listings (
    id              UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    host_profile_id UUID                        NOT NULL REFERENCES host_profiles(id) ON DELETE RESTRICT,

    -- Location (PostGIS)
    address_line1   VARCHAR(200)                NOT NULL,
    city            VARCHAR(100)                NOT NULL,
    postcode        VARCHAR(10)                 NOT NULL,
    latitude        NUMERIC(10, 7)              NOT NULL,
    longitude       NUMERIC(10, 7)              NOT NULL,

    -- Description
    title           VARCHAR(150)                NOT NULL,
    description     TEXT,

    -- Pricing (pence)
    price_pence     INT                         NOT NULL,
    price_unit      parking_price_unit          NOT NULL DEFAULT 'per_hour',
    min_duration_minutes INT                    NOT NULL DEFAULT 60,
    max_duration_hours   INT,

    -- Availability (same structure as charger_listings)
    available_from  TIME,
    available_to    TIME,
    available_days  SMALLINT[]                  DEFAULT '{1,2,3,4,5,6,0}', -- 0=Sunday ISO day

    -- Features
    is_ev_dedicated     BOOLEAN                 NOT NULL DEFAULT FALSE,
    has_cctv            BOOLEAN                 NOT NULL DEFAULT FALSE,
    is_covered          BOOLEAN                 NOT NULL DEFAULT FALSE,
    is_disabled_access  BOOLEAN                 NOT NULL DEFAULT FALSE,

    -- Status & stats
    status          parking_listing_status      NOT NULL DEFAULT 'draft',
    view_count      INT                         NOT NULL DEFAULT 0,
    booking_count   INT                         NOT NULL DEFAULT 0,
    average_rating  NUMERIC(3, 2)               DEFAULT NULL,
    review_count    INT                         NOT NULL DEFAULT 0,

    created_at      TIMESTAMPTZ                 NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ                 NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_parking_listings_location ON parking_listings (latitude, longitude);
CREATE INDEX idx_parking_listings_host     ON parking_listings (host_profile_id);
CREATE INDEX idx_parking_listings_status   ON parking_listings (status) WHERE status = 'published';
CREATE INDEX idx_parking_listings_city     ON parking_listings (city, status);

CREATE TRIGGER trg_parking_listings_updated_at
    BEFORE UPDATE ON parking_listings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Parking bookings (simpler than charging — no OCPP, no session)
CREATE TABLE parking_bookings (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id          UUID        NOT NULL REFERENCES parking_listings(id),
    driver_profile_id   UUID        NOT NULL REFERENCES driver_profiles(id),

    starts_at           TIMESTAMPTZ NOT NULL,
    ends_at             TIMESTAMPTZ NOT NULL,
    duration_minutes    INT         NOT NULL,

    -- Pricing snapshot (pence)
    unit_price_pence    INT         NOT NULL,
    total_pence         INT         NOT NULL,
    platform_fee_pence  INT         NOT NULL DEFAULT 0,
    host_payout_pence   INT         NOT NULL,

    -- Payment
    stripe_pi_id        VARCHAR(100),
    status              VARCHAR(30) NOT NULL DEFAULT 'pending',
    -- pending | confirmed | completed | cancelled | refunded

    vehicle_plate       VARCHAR(15),  -- optional: for ANPR / access control

    cancelled_at        TIMESTAMPTZ,
    cancellation_reason TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_parking_bookings_listing ON parking_bookings (listing_id, starts_at);
CREATE INDEX idx_parking_bookings_driver  ON parking_bookings (driver_profile_id, starts_at DESC);

CREATE TRIGGER trg_parking_bookings_updated_at
    BEFORE UPDATE ON parking_bookings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- MODULE O — ESG / CARBON DATA PRODUCTS
-- Per-session carbon data, cumulative platform metrics,
-- and subscription tiers for B2B ESG reporting.
-- ============================================================

CREATE TYPE esg_report_format AS ENUM (
    'csv',
    'json',
    'pdf'
);

CREATE TYPE esg_subscription_tier AS ENUM (
    'free',            -- rolling 30-day summary only
    'standard',        -- monthly export, 12-month history
    'premium'          -- API access, custom date range, multiple formats, CO2e certificates
);

-- Per-session carbon record (written by SessionService when session completes)
CREATE TABLE session_carbon_records (
    id              BIGSERIAL   PRIMARY KEY,
    session_id      UUID        NOT NULL REFERENCES charging_sessions(id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Energy data (from charging_sessions.energy_consumed_wh)
    energy_wh       INT         NOT NULL,

    -- Grid carbon intensity at time of session (g CO2e/kWh)
    -- Pulled from National Grid ESO API (UK) or ENTSO-E (EU)
    grid_intensity_gco2_per_kwh NUMERIC(7, 2),

    -- Calculated CO2 saved vs petrol equivalent
    co2_saved_grams INT,        -- vs average UK petrol car at 120g CO2/km, 7.5L/100km
    km_equivalent   NUMERIC(8, 2),  -- km this charge could power

    -- Tree equivalent (for consumer-friendly display)
    tree_hours_equivalent NUMERIC(8, 2),

    -- Region at time of session
    region_code     VARCHAR(10),
    grid_provider   VARCHAR(50),

    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_carbon_records_session ON session_carbon_records (session_id);
CREATE INDEX idx_carbon_records_user    ON session_carbon_records (user_id, recorded_at DESC);
CREATE INDEX idx_carbon_records_region  ON session_carbon_records (region_code, recorded_at DESC);


-- Cumulative ESG totals per user (denormalised, updated by trigger)
CREATE TABLE user_esg_totals (
    user_id                 UUID        PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    total_energy_wh         BIGINT      NOT NULL DEFAULT 0,
    total_co2_saved_grams   BIGINT      NOT NULL DEFAULT 0,
    total_sessions          INT         NOT NULL DEFAULT 0,
    total_km_equivalent     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ESG report exports log (for B2B / fleet / SMB)
CREATE TABLE esg_report_exports (
    id              UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID                    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fleet_account_id UUID                   REFERENCES fleet_accounts(id) ON DELETE SET NULL,

    format          esg_report_format       NOT NULL DEFAULT 'csv',
    tier            esg_subscription_tier   NOT NULL DEFAULT 'free',

    date_from       DATE                    NOT NULL,
    date_to         DATE                    NOT NULL,

    row_count       INT,
    file_url        TEXT,                   -- Railway / S3 pre-signed download URL
    expires_at      TIMESTAMPTZ,            -- download link expiry (24 hrs)

    created_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_esg_exports_user  ON esg_report_exports (user_id, created_at DESC);
CREATE INDEX idx_esg_exports_fleet ON esg_report_exports (fleet_account_id) WHERE fleet_account_id IS NOT NULL;


-- Platform-wide ESG totals (single row, updated by pg_cron nightly)
CREATE TABLE platform_esg_totals (
    id                      INT             PRIMARY KEY DEFAULT 1,
    total_sessions          BIGINT          NOT NULL DEFAULT 0,
    total_energy_kwh        NUMERIC(14, 3)  NOT NULL DEFAULT 0,
    total_co2_saved_tonnes  NUMERIC(12, 4)  NOT NULL DEFAULT 0,
    total_km_equivalent     BIGINT          NOT NULL DEFAULT 0,
    unique_drivers          INT             NOT NULL DEFAULT 0,
    last_calculated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT platform_esg_singleton CHECK (id = 1)
);

INSERT INTO platform_esg_totals DEFAULT VALUES ON CONFLICT DO NOTHING;


-- ============================================================
-- MODULE Q — WHITE-LABEL & PARTNER API TENANTS
-- Allows third-party operators (e.g. housing associations,
-- councils, hospitality) to run Zipgrid under their brand.
-- ============================================================

CREATE TYPE tenant_status AS ENUM (
    'trial',       -- 30-day evaluation
    'active',      -- paying tenant
    'suspended',   -- payment lapsed
    'churned'
);

CREATE TABLE api_tenants (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_name         VARCHAR(200)    NOT NULL,
    slug                VARCHAR(60)     NOT NULL UNIQUE,    -- e.g. 'nexus-coworking'
    status              tenant_status   NOT NULL DEFAULT 'trial',

    -- API credentials
    api_key_hash        VARCHAR(128)    NOT NULL,           -- bcrypt of the live API key
    api_key_prefix      VARCHAR(12)     NOT NULL,           -- first 12 chars for identification (e.g. 'zg_live_abc1')

    -- White-label config
    custom_domain       VARCHAR(253),                       -- e.g. 'charging.nexus.co.uk'
    brand_name          VARCHAR(100),
    brand_logo_url      TEXT,
    brand_primary_colour VARCHAR(7),                        -- hex, e.g. '#1A56DB'

    -- Billing (Stripe subscription)
    stripe_customer_id      VARCHAR(100),
    stripe_subscription_id  VARCHAR(100),
    plan_name               VARCHAR(50) DEFAULT 'growth',   -- starter | growth | enterprise

    -- Rate limits
    rate_limit_per_minute   INT         NOT NULL DEFAULT 100,
    rate_limit_per_day      INT         NOT NULL DEFAULT 10000,

    -- Contact
    admin_email             VARCHAR(254) NOT NULL,
    admin_user_id           UUID         REFERENCES users(id),

    trial_ends_at           TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_api_tenants_slug   ON api_tenants (slug);
CREATE INDEX idx_api_tenants_status ON api_tenants (status) WHERE status IN ('trial', 'active');

CREATE TRIGGER trg_api_tenants_updated_at
    BEFORE UPDATE ON api_tenants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- API usage metering (per-key, per-day aggregates)
CREATE TABLE api_tenant_usage (
    id              BIGSERIAL   PRIMARY KEY,
    tenant_id       UUID        NOT NULL REFERENCES api_tenants(id) ON DELETE CASCADE,
    usage_date      DATE        NOT NULL DEFAULT CURRENT_DATE,
    endpoint        VARCHAR(100) NOT NULL,
    request_count   INT         NOT NULL DEFAULT 0,
    error_count     INT         NOT NULL DEFAULT 0,

    CONSTRAINT uq_tenant_usage_day_endpoint UNIQUE (tenant_id, usage_date, endpoint)
);

CREATE INDEX idx_api_usage_tenant_date ON api_tenant_usage (tenant_id, usage_date DESC);


-- ============================================================
-- MODULE S — V2G / GRID SERVICES (SCHEDULING HOOKS)
-- Vehicle-to-Grid and smart charging export scheduling.
-- Stores scheduled grid export events triggered by tariff engine.
-- Actual V2G hardware interaction deferred to Phase 4 hardware partners.
-- ============================================================

CREATE TYPE grid_schedule_type AS ENUM (
    'smart_charge',         -- standard optimised charge (off-peak)
    'v2g_export',           -- export stored energy to grid
    'demand_response',      -- reduce charge rate on grid request
    'solar_priority'        -- charge from solar when available
);

CREATE TYPE grid_schedule_status AS ENUM (
    'scheduled',
    'executing',
    'completed',
    'cancelled',
    'failed'
);

CREATE TABLE grid_schedules (
    id                  UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID                    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vehicle_id          UUID                    REFERENCES driver_vehicles(id) ON DELETE SET NULL,
    listing_id          UUID                    REFERENCES charger_listings(id) ON DELETE SET NULL,

    type                grid_schedule_type      NOT NULL DEFAULT 'smart_charge',
    status              grid_schedule_status    NOT NULL DEFAULT 'scheduled',

    -- Window
    window_start        TIMESTAMPTZ             NOT NULL,
    window_end          TIMESTAMPTZ             NOT NULL,

    -- Target parameters
    target_soc_pct      SMALLINT CHECK (target_soc_pct BETWEEN 0 AND 100),
    max_charge_kw       NUMERIC(6,2),
    max_export_kw       NUMERIC(6,2),

    -- Tariff context at scheduling time
    tariff_name         VARCHAR(60),            -- e.g. 'octopus_agile'
    expected_rate_pence_per_kwh NUMERIC(6,2),

    -- Outcome
    actual_energy_wh    INT,
    resulting_session_id UUID                   REFERENCES charging_sessions(id),

    -- AI agent that created this
    created_by_agent    BOOLEAN                 NOT NULL DEFAULT FALSE,
    agent_task_id       UUID,

    created_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_grid_schedules_user   ON grid_schedules (user_id, window_start);
CREATE INDEX idx_grid_schedules_status ON grid_schedules (status, window_start) WHERE status = 'scheduled';

CREATE TRIGGER trg_grid_schedules_updated_at
    BEFORE UPDATE ON grid_schedules
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- DRIVER PLUS — SUBSCRIPTION TRACKING
-- Tracks active Driver Plus subscriptions (streamed from Stripe).
-- Revenue stream S9 from 1.5-revenue-model.md.
-- ============================================================

CREATE TYPE subscription_status AS ENUM (
    'trialing',
    'active',
    'past_due',
    'cancelled',
    'unpaid',
    'paused'
);

CREATE TABLE driver_subscriptions (
    id                      UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID                    NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Stripe
    stripe_subscription_id  VARCHAR(100)            NOT NULL UNIQUE,
    stripe_price_id         VARCHAR(100)            NOT NULL,

    -- Plan
    plan_name               VARCHAR(50)             NOT NULL DEFAULT 'driver_plus',
    -- driver_plus | driver_plus_annual
    price_pence_per_period  INT                     NOT NULL,
    billing_period          VARCHAR(10)             NOT NULL DEFAULT 'monthly', -- monthly | annual

    -- Status
    status                  subscription_status     NOT NULL DEFAULT 'trialing',
    trial_end               TIMESTAMPTZ,
    current_period_start    TIMESTAMPTZ,
    current_period_end      TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    cancel_at_period_end    BOOLEAN                 NOT NULL DEFAULT FALSE,

    -- Benefits tracking
    advance_booking_days    SMALLINT                NOT NULL DEFAULT 14,  -- 48h standard → 14 days Plus
    fee_discount_pct        SMALLINT                NOT NULL DEFAULT 10,  -- 10% session fee discount

    created_at              TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ             NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_driver_subs_user   ON driver_subscriptions (user_id);
CREATE INDEX idx_driver_subs_status ON driver_subscriptions (status) WHERE status IN ('trialing', 'active');

CREATE TRIGGER trg_driver_subs_updated_at
    BEFORE UPDATE ON driver_subscriptions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- OCPI ROAMING SESSIONS
-- Phase 3: interoperability with public charge point networks.
-- Stores roaming sessions initiated via OCPI 2.2.1 CPO/eMSP roles.
-- ============================================================

CREATE TYPE ocpi_role AS ENUM (
    'cpo',   -- Charge Point Operator — Zipgrid hosts the charger
    'emsp'   -- e-Mobility Service Provider — Zipgrid driver roams to partner charger
);

CREATE TABLE ocpi_roaming_sessions (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    ocpi_session_id     VARCHAR(100) NOT NULL,              -- OCPI session.id from partner
    ocpi_country_code   VARCHAR(2)  NOT NULL DEFAULT 'GB',
    ocpi_party_id       VARCHAR(3)  NOT NULL,               -- partner operator code
    role                ocpi_role   NOT NULL,

    -- Zipgrid side
    user_id             UUID        REFERENCES users(id),
    listing_id          UUID        REFERENCES charger_listings(id),

    -- Energy & cost
    energy_wh           INT,
    total_cost_pence    INT,
    currency            VARCHAR(3)  NOT NULL DEFAULT 'GBP',

    -- Timestamps
    started_at          TIMESTAMPTZ,
    ended_at            TIMESTAMPTZ,

    -- Raw OCPI payload (for debugging / disputes)
    raw_start_payload   JSONB,
    raw_end_payload     JSONB,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_ocpi_session UNIQUE (ocpi_country_code, ocpi_party_id, ocpi_session_id)
);

CREATE INDEX idx_ocpi_sessions_user    ON ocpi_roaming_sessions (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_ocpi_sessions_listing ON ocpi_roaming_sessions (listing_id) WHERE listing_id IS NOT NULL;
CREATE INDEX idx_ocpi_sessions_date    ON ocpi_roaming_sessions (started_at DESC);

CREATE TRIGGER trg_ocpi_sessions_updated_at
    BEFORE UPDATE ON ocpi_roaming_sessions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- BLOG THREADS
-- Community posts linked to blog articles from the content system.
-- Allows Contentlayer/MDX articles to have discussion threads.
-- ============================================================

CREATE TABLE blog_post_threads (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    article_slug    VARCHAR(200) NOT NULL UNIQUE,   -- matches Contentlayer slug
    title           VARCHAR(300) NOT NULL,
    is_open         BOOLEAN     NOT NULL DEFAULT TRUE,
    reply_count     INT         NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_blog_threads_slug ON blog_post_threads (article_slug);

-- Replies on blog threads reuse community_replies with post_id = NULL
-- and a separate blog_thread_id FK (optional extension pattern)


-- ============================================================
-- MIGRATION COMPLETE
-- Run after: 014_user_preferences_referrals_saved.sql
-- ============================================================
